#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpinfo-cm
data:
  index.php: <?php phpinfo();?>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpinfo
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      - 
        args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:8080
        command:
        - php
        image: php
        name: phpinfo-container
        ports:
        - containerPort: 8080
        volumeMounts:
        - 
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: index.php
        workingDir: /src/
      volumes:
      - 
        configMap:
          defaultMode: 0400
          items: 
          -
            key: index.php
            mode: 0400
            path: index.php
          name: phpinfo-cm
        name: phpinfo-volume
---
apiVersion: v1
kind: Service
metadata:
  name: phpinfo
spec:
  ports:
  - 
    port: 80
    targetPort: 8080
  selector:
    app: phpinfo
  type: ClusterIP
---
