# Default values for phpinfo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

containerPort: 8080

protocol: TCP

containers:
  args:
    - -f
    - index.php
    - -S
    - 0.0.0.0:8080
  command:
    - php
  livenessProbe:
    httpGet:
      path: /
      port: 8080
  ports:
    - containerPort: 8080
      protocol: TCP
  readinessProbe:
    httpGet:
      path: /
      port: 8080
  volumeMounts:
    - 
      mountPath: /src/index.php
      name: phpinfo-volume
      readOnly: true
      subPath: index.php
  workingDir: /src/
  
volumes:
  - 
    configMap:
      defaultMode: 0400
      items: 
        -
          key: index.php
          mode: 0400
          path: index.php
      name: phpinfo-cm
    name: phpinfo-volume

image:
  repository: php
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.4.27-zts-buster"

imagePullSecrets:
  - name: docker-login
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
