################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: CI                                                                       #
on:                                                                            #
  push:                                                                        #
    branches:                                                                  #
    - 2022-01                                                                  #
jobs:                                                                          #
  docker:                                                                      #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: run                                                                #
      run:                                                                     >
        docker run -d --entrypoint php --name phpinfo -p 30000:8080            \
          -v $PWD/src/index.php:/src/index.php:ro -w /src/                     \
          docker.io/library/php:latest -f index.php -S 0.0.0.0:8080            ;
    - name: test                                                               #
      run:                                                                     |
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            ip=$( ip r | grep -v docker | awk '/kernel/{ print $9 }' )         ;
            curl ${ip}:30000 | grep "PHP.*phpinfo()" && break                  ;
          done                                                                 ;
                                                                               #
  swarm:                                                                       #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: init                                                               #
      run: docker swarm init                                                   ;
    - name: deploy                                                             #
      run: docker stack deploy -c docker-compose.yaml phpinfo                  ;
    - name: test                                                               #
      run:                                                                     |
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            ip=$( ip r | grep -v docker | awk '/kernel/{ print $9 }' )         ;
            curl ${ip}:30000 | grep "PHP.*phpinfo()" && break                  ;
          done                                                                 ;
                                                                               #
  kubernetes:                                                                  #
    env:                                                                       #
      mode: kubernetes                                                         #
    runs-on: ubuntu-18.04                                                      #
    steps:                                                                     #
    - name: checkout                                                           #
      uses: actions/checkout@v2                                                #
    - name: build                                                              #
      run: docker build -t phpinfo:2022-01 .                                   ;
    - name: init                                                               #
      run:                                                                     |
        uuid=$( md5sum kube-compose.yaml | cut -d\  -f1 )                      ;
        git clone --single-branch -b v1.2                                      \
          https://github.com/academiaonline/kubernetes $uuid                   ;
        path=$uuid/bin/cluster/ubuntu18/install-docker-kubelet.sh              ;
        source $path                                                           ;
        path=$uuid/bin/cluster/ubuntu18/install-leader.sh                      ;
        source $path                                                           ;
        master=$( kubectl get node | grep master | awk '{ print $1 }' )        ;
        kubectl taint node $master node-role.kubernetes.io/master:NoSchedule-  ;
        rm -rf $uuid                                                           ;
    - name: apply                                                              #
      run: kubectl apply -f kube-compose.yaml                                  ;
    - name: test                                                               #
      run:                                                                     |
        set -x                                                                 ;
        while true                                                             ;
          do                                                                   \
            sleep 10                                                           ;
            ip=$( ip r | grep -v docker | grep kern -m1 | awk '{ print $9 }' ) ;
            curl ${ip}:30000 | grep "PHP.*phpinfo()" && break                  ;
          done                                                                 ;
################################################################################
